# Generated by Django 2.0 on 2018-02-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcondition',
            name='key_word',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
